from __future__ import annotations

DATASETS = [
    "data/processed/mbti_questions.csv",
    "data/processed/machine_mindset_self_awareness_sample30.jsonl",
    "data/processed/ifeval_sample30.jsonl",
]

DATASET_SAMPLE_LIMITS = {
    "data/processed/mbti_questions.csv": 93,
    "data/processed/machine_mindset_self_awareness_sample30.jsonl": 30,
    "data/processed/ifeval_sample30.jsonl": 30,
}

RQ2_STRONG_PREMISE_KEEP = [
    "INTJ",
    "INFJ",
    "ENFJ",
]

RQ2_STRONG_PREMISE_RERUN_13 = [
    "ESFP",
    "ISFJ",
    "ENTJ",
    "ENTP",
    "ESTP",
    "ISTP",
    "ISFP",
    "ENFP",
    "ISTJ",
    "INTP",
    "INFP",
    "ESFJ",
    "ESTJ",
]

RQ2_PREMISE_MBTI = [
    "INTJ",
    "INFJ",
    "ENFJ",
    "ISFJ",
    "ENTJ",
    "ENTP",
    "ISTP",
    "ENFP",
    "ISTJ",
    "INFP",
    "ESFJ",
    "ESTJ",
]

RQ2_PAIRS = [
    {"A": "ISFJ", "B": "ENTP"},
    {"A": "ISFJ", "B": "ISTP"},
    {"A": "ISFJ", "B": "ENFP"},
    {"A": "ISFJ", "B": "INFP"},
    {"A": "ENTP", "B": "ENFJ"},
    {"A": "ENTP", "B": "ISFJ"},
    {"A": "ENTP", "B": "ENTJ"},
    {"A": "ENTP", "B": "ISTP"},
    {"A": "ENTP", "B": "ESFJ"},
    {"A": "ISTJ", "B": "INTJ"},
    {"A": "ISTJ", "B": "ENTJ"},
    {"A": "ISTJ", "B": "ENTP"},
    {"A": "ISTJ", "B": "ISTP"},
    {"A": "ISTJ", "B": "ENFP"},
    {"A": "ISTJ", "B": "INFP"},
    {"A": "ESTJ", "B": "ENTJ"},
    {"A": "INTJ", "B": "INFJ"},
    {"A": "INTJ", "B": "ENFJ"},
    {"A": "INTJ", "B": "ISFJ"},
    {"A": "INTJ", "B": "ENTJ"},
    {"A": "INTJ", "B": "ENTP"},
    {"A": "INTJ", "B": "ISTP"},
    {"A": "INTJ", "B": "ENFP"},
    {"A": "INTJ", "B": "INFP"},
    {"A": "INTJ", "B": "ESFJ"},
    {"A": "INTJ", "B": "ESTJ"},
    {"A": "INFJ", "B": "INFP"},
    {"A": "ENFJ", "B": "INTJ"},
    {"A": "ENFJ", "B": "INFJ"},
    {"A": "ENFJ", "B": "ISFJ"},
]

RQ2_BATCH2_PAIRS = [
    {"A": "ENFJ", "B": "ENTJ"},
    {"A": "ENFJ", "B": "ENTP"},
    {"A": "ENFJ", "B": "ISTP"},
    {"A": "ENFJ", "B": "ENFP"},
    {"A": "ENFJ", "B": "ISTJ"},
    {"A": "ENFJ", "B": "INFP"},
    {"A": "ENFJ", "B": "ESFJ"},
    {"A": "ENFJ", "B": "ESTJ"},
    {"A": "ISFJ", "B": "INTJ"},
    {"A": "ISFJ", "B": "INFJ"},
    {"A": "ISFJ", "B": "ENFJ"},
    {"A": "ISFJ", "B": "ENTJ"},
    {"A": "ISFJ", "B": "ISTJ"},
    {"A": "ISFJ", "B": "ESFJ"},
    {"A": "ISFJ", "B": "ESTJ"},
    {"A": "ENTJ", "B": "INTJ"},
    {"A": "ENTJ", "B": "INFJ"},
    {"A": "ENTJ", "B": "ENFJ"},
    {"A": "ENTJ", "B": "ISFJ"},
    {"A": "ENTJ", "B": "ENTP"},
    {"A": "ENTJ", "B": "ISTP"},
    {"A": "ENTJ", "B": "ENFP"},
    {"A": "ENTJ", "B": "ISTJ"},
    {"A": "ENTJ", "B": "INFP"},
    {"A": "ENTJ", "B": "ESFJ"},
    {"A": "ENTP", "B": "INTJ"},
    {"A": "ENTP", "B": "INFJ"},
    {"A": "ENTP", "B": "ENFP"},
    {"A": "ENTP", "B": "ISTJ"},
    {"A": "ENTP", "B": "INFP"},
    {"A": "ENFP", "B": "ISFJ"},
    {"A": "ENFP", "B": "ISTP"},
    {"A": "ENFP", "B": "ISTJ"},
    {"A": "ENFP", "B": "INFP"},
    {"A": "ENFP", "B": "ESFJ"},
    {"A": "ENFP", "B": "ESTJ"},
]

RQ3_PAIRS = [
    {"A": "INTJ", "B": "ISTJ"},
    {"A": "INFJ", "B": "INTJ"},
    {"A": "INFJ", "B": "ENFJ"},
    {"A": "INFJ", "B": "ISFJ"},
    {"A": "INFJ", "B": "ENTJ"},
    {"A": "INFJ", "B": "ENTP"},
    {"A": "INFJ", "B": "ISTP"},
    {"A": "INFJ", "B": "ENFP"},
    {"A": "INFJ", "B": "ISTJ"},
    {"A": "INFJ", "B": "ESFJ"},
    {"A": "INFJ", "B": "ESTJ"},
    {"A": "ENTJ", "B": "ESTJ"},
    {"A": "ISTP", "B": "INTJ"},
    {"A": "ISTP", "B": "INFJ"},
    {"A": "ISTP", "B": "ENFJ"},
    {"A": "ISTP", "B": "ISFJ"},
    {"A": "ISTP", "B": "ENTP"},
    {"A": "ISTP", "B": "ENFP"},
    {"A": "ISTP", "B": "ISTJ"},
    {"A": "ISTP", "B": "INFP"},
    {"A": "ISTP", "B": "ESFJ"},
    {"A": "ISTP", "B": "ESTJ"},
    {"A": "ENFP", "B": "INFJ"},
    {"A": "ENFP", "B": "ENTJ"},
    {"A": "ENFP", "B": "ENTP"},
    {"A": "ESTJ", "B": "ISTJ"},
    {"A": "ENTP", "B": "ESTJ"},
    {"A": "ISTP", "B": "ENTJ"},
    {"A": "ENFP", "B": "INTJ"},
    {"A": "ENFP", "B": "ENFJ"},
]

RQ3_BATCH2_PAIRS = [
    {"A": "ISTJ", "B": "INFJ"},
    {"A": "ISTJ", "B": "ENFJ"},
    {"A": "ISTJ", "B": "ISFJ"},
    {"A": "ISTJ", "B": "ESFJ"},
    {"A": "ISTJ", "B": "ESTJ"},
    {"A": "INFP", "B": "INTJ"},
    {"A": "INFP", "B": "INFJ"},
    {"A": "INFP", "B": "ENFJ"},
    {"A": "INFP", "B": "ISFJ"},
    {"A": "INFP", "B": "ENTJ"},
    {"A": "INFP", "B": "ENTP"},
    {"A": "INFP", "B": "ISTP"},
    {"A": "INFP", "B": "ENFP"},
    {"A": "INFP", "B": "ISTJ"},
    {"A": "INFP", "B": "ESFJ"},
    {"A": "INFP", "B": "ESTJ"},
    {"A": "ESFJ", "B": "INTJ"},
    {"A": "ESFJ", "B": "INFJ"},
    {"A": "ESFJ", "B": "ENFJ"},
    {"A": "ESFJ", "B": "ISFJ"},
    {"A": "ESFJ", "B": "ENTJ"},
    {"A": "ESFJ", "B": "ENTP"},
    {"A": "ESFJ", "B": "ISTP"},
    {"A": "ESFJ", "B": "ENFP"},
    {"A": "ESFJ", "B": "ISTJ"},
    {"A": "ESFJ", "B": "INFP"},
    {"A": "ESFJ", "B": "ESTJ"},
    {"A": "ESTJ", "B": "INTJ"},
    {"A": "ESTJ", "B": "INFJ"},
    {"A": "ESTJ", "B": "ENFJ"},
    {"A": "ESTJ", "B": "ISFJ"},
    {"A": "ESTJ", "B": "ENTP"},
    {"A": "ESTJ", "B": "ISTP"},
    {"A": "ESTJ", "B": "ENFP"},
    {"A": "ESTJ", "B": "INFP"},
    {"A": "ESTJ", "B": "ESFJ"},
]

RQ2_CONDITIONS = [
    "A_history_to_B_strong",
    "A_summary_to_B_strong",
    "B_history_to_B_strong",
    "B_summary_to_B_strong",
]

RQ3_CONDITIONS = [
    "A3_history_to_B",
    "A3_summary_to_B",
    "B3_history_to_B",
    "B3_summary_to_B",
]
